### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by Mancy** [TravelTimN/ci-milestone02-ifd#1]
Hello there,
the Airport timezone is not featured in your iataData.json file will you add it ?

**Comment by TravelTimN** [comment]
@Mancy this was part of a project I made for my Code Institute studies. I might look into adding more details like an airport timezone feature later, but it's not a priority right now for me. Thanks for the suggestion!

**Comment by TravelTimN** [comment]
@Mancy - good news! I've added some new features to the project, including the location timezone data. This will now be closed. Hope it's satisfactory to your request!
